In [1]:
import pandas as pd
file_data = pd.read_csv(r'/content/recipes_muffins_cupcakes.csv')

In [5]:
file_data.head(20)

       Type  Flour  Milk  Sugar  Butter  Egg  Baking Powder  Vanilla  Salt
0    Muffin     55    28      3       7    5              2        0     0
1    Muffin     47    24     12       6    9              1        0     0
2    Muffin     47    23     18       6    4              1        0     0
3    Muffin     45    11     17      17    8              1        0     0
4    Muffin     50    25     12       6    5              2        1     0
5    Muffin     55    27      3       7    5              2        1     0
6    Muffin     54    27      7       5    5              2        0     0
7    Muffin     47    26     10      10    4              1        0     0
8    Muffin     50    17     17       8    6              1        0     0
9    Muffin     50    17     17      11    4              1        0     0
10  Cupcake     39     0     26      19   14              1        1     0
11  Cupcake     42    21     16      10    8              3        0     0
12  Cupcake     34    17     20      20    5              2        1     0
13  Cupcake     39    13     17      19   10              1        1     0
14  Cupcake     38    15     23      15    8              0        1     0
15  Cupcake     42    18     25       9    5              1        0     0
16  Cupcake     36    14     21      14   11              2        1     0
17  Cupcake     38    15     31       8    6              1        1     0
18  Cupcake     36    16     24      12    9              1        1     0
19  Cupcake     34    17     23      11   13              0        1     0

In [8]:
ingredients = ['Flour','Milk','Sugar','Butter','Egg','Baking Powder','Vanilla','Salt']
X = file_data[ingredients]

In [9]:
y = file_data['Type']

In [10]:
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

clf = GradientBoostingClassifier(random_state=0)
clf.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [11]:
clf.score(X,y)

1.0